version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
         name: install tex
         command: |
          apt-get update && apt-get -y install \
            --no-install-recommends \
            ca-certificates \
            make \
            texlive-latex-base \
            texlive-latex-recommended \
            texlive-latex-extra \
            texlive-fonts-recommended \
            texlive-bibtex-extra \
            git \
            python3


      - run:
          name: finish cloning submodules
          command: |
            git submodule init
            git submodule update

      - run:
          name: build draft
          command: |
            make draft
            test -f draft.pdf

      - store_artifacts:
          path: draft.pdf
          destination: draft.pdf

      - run:
          name: check person-month data
          command: |
            ./check-pdata


workflows:
  version: 2
  default:
    jobs:
      - build
